services:
    caddy:
        image: caddy:latest
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
    app:
        # build:
        #     context: .
        #     dockerfile: Xdebug.Dockerfile
        # image: customxdebug
        image: ghcr.io/divblox-group/php-apache-base-docker-image:latest
        volumes:
            - ./sdev:/var/www/html/ #bind your source
        extra_hosts:
            - appname.dxgroup.local:host-gateway
            - host.docker.internal:host-gateway # for xdebug
        env_file:
            - sdev.env # or divbloxphp.env or create app specific files
    sql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "dxuser"
            MYSQL_PASSWORD: "secret"
            MYSQL_DATABASE: "dxdatabase"
        volumes:
            - mysql8_data:/var/lib/mysql
        command:
            - --default-authentication-plugin=caching_sha2_password
            - --lower_case_table_names=1
            - --sql_mode=
        ports:
            - 3306:3306
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command: redis-server --save 1 1 --requirepass 123
        volumes:
            - redis_data:/data
    redisinsight:
        image: redis/redisinsight:latest
        ports:
            - 5540:5540
        volumes:
            - redisinsight_data:/data
    maildev:
        image: maildev/maildev:latest
        ports:
            - 1080:80
            - 1025:25
        environment:
            MAILDEV_SMTP_PORT: "25"
            MAILDEV_WEB_PORT: "80"
            MAILDEV_INCOMING_USER: "maildev@maildev.dev"
            MAILDEV_INCOMING_PASS: "secret"
            MAILDEV_WEB_USER: "admin"
            MAILDEV_WEB_PASS: "admin"
volumes:
    mysql8_data:
    caddy_data:
    caddy_config:
    redis_data:
    redisinsight_data:
